name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.5

dependencies:
  nitric_sdk:
    path: ../
  uuid: ^4.3.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
